repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src|scripts|tests)/
      - id: ruff-format
        files: ^(src|scripts|tests)/

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run --extra dev mypy src
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: uv run --extra dev pytest tests/
        language: system
        pass_filenames: false
        always_run: true
