paths:
  root_dir: "."
  data_dir: "data"
  audio_dir: "data/audio"
  manifests_dir: "data/manifests"
  individual_manifests_dir: "data/manifests/individual"
  final_manifests_dir: "data/manifests/final"
  final_train_manifest: "data/manifests/final/train_final.jsonl"
  final_val_manifest: "data/manifests/final/val_final.jsonl"
  final_test_manifest: "data/manifests/final/test_final.jsonl"

run:
  target_sr: 16000
  skip_existing: true
  do_train: true
  do_val: true
  shuffle_seed: 42
  lowercase_text: true
  normalize_peak: true
  max_failures: 10000
  sample_per_dataset: null

hf:
  token_env: "HF_TOKEN"

datasets:
  train:
    - name: "bigos_v2_train"
      hf_id: "amu-cai/pl-asr-bigos-v2"
      config_name: "pwr-azon_read-20"
      split: "train"
      lang: "pl"
      samples: 5
      text_col: "ref_orig"
      audio_col: "audio"
      use_streaming: false

    - name: "pelcra_pl_train"
      hf_id: "pelcra/pl-asr-pelcra-for-bigos"
      config_name: "ul-spokes_mix_luz-18"
      split: "train"
      lang: "pl"
      samples: 5
      text_col: "ref_orig"
      audio_col: "audio"
      use_streaming: false

    - name: "cv21_pl_train"
      hf_id: "fsicoli/common_voice_21_0"
      config_name: "pl"
      split: "train"
      lang: "pl"
      samples: 5
      text_col: "sentence"
      audio_col: "audio"
      use_streaming: true

    - name: "mls_pl_train"
      hf_id: "facebook/multilingual_librispeech"
      config_name: "polish"
      split: "train"
      lang: "pl"
      samples: 5
      text_col: "transcript"
      audio_col: "audio"
      use_streaming: false

    - name: "librispeech_train"
      hf_id: "openslr/librispeech_asr"
      config_name: "clean"
      split: "train.360"
      lang: "en"
      samples: 5
      text_col: "text"
      audio_col: "audio"
      use_streaming: true

    - name: "cv21_en_train"
      hf_id: "fsicoli/common_voice_21_0"
      config_name: "en"
      split: "train"
      lang: "en"
      samples: 5
      text_col: "sentence"
      audio_col: "audio"
      use_streaming: true

    - name: "fleurs_pl_train"
      hf_id: "google/fleurs"
      config_name: "pl_pl"
      split: "train"
      lang: "pl"
      samples: 5
      text_col: "transcription"
      audio_col: "audio"
      use_streaming: false

  val:
    - name: "bigos_pl_clean_val"
      hf_id: "amu-cai/pl-asr-bigos-v2"
      config_name: "pwr-azon_read-20"
      split: "validation"
      lang: "pl"
      samples: 5
      text_col: "ref_orig"
      audio_col: "audio"
      use_streaming: false

    - name: "bigos_pl_noisy_val"
      hf_id: "amu-cai/pl-asr-bigos-v2"
      config_name: "pwr-azon_spont-20"
      split: "train"
      lang: "pl"
      samples: 5
      text_col: "ref_orig"
      audio_col: "audio"
      use_streaming: false

    - name: "librispeech_val"
      hf_id: "openslr/librispeech_asr"
      config_name: "clean"
      split: "validation"
      lang: "en"
      samples: 5
      text_col: "text"
      audio_col: "audio"
      use_streaming: true

    - name: "cv21_pl_val"
      hf_id: "fsicoli/common_voice_21_0"
      config_name: "pl"
      split: "validation"
      lang: "pl"
      samples: 5
      text_col: "sentence"
      audio_col: "audio"
      use_streaming: true

    - name: "cv21_en_val"
      hf_id: "fsicoli/common_voice_21_0"
      config_name: "en"
      split: "validation"
      lang: "en"
      samples: 5
      text_col: "sentence"
      audio_col: "audio"
      use_streaming: true

    - name: "fleurs_pl_val"
      hf_id: "google/fleurs"
      config_name: "pl_pl"
      split: "validation"
      lang: "pl"
      samples: 5
      text_col: "transcription"
      audio_col: "audio"
      use_streaming: false

    - name: "fleurs_en_val"
      hf_id: "google/fleurs"
      config_name: "en_us"
      split: "validation"
      lang: "en"
      samples: 5
      text_col: "transcription"
      audio_col: "audio"
      use_streaming: false

    - name: "pelcra_pl_val"
      hf_id: "pelcra/pl-asr-pelcra-for-bigos"
      config_name: "ul-spokes_mix_luz-18"
      split: "validation"
      lang: "pl"
      samples: 5
      text_col: "ref_orig"
      audio_col: "audio"
      use_streaming: false
